const ROLES = {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    SALON_OWNER: "SALON_OWNER",
    BRANCH_MANAGER: "BRANCH_MANAGER",
    STAFF: "STAFF",
    CUSTOMER: "CUSTOMER"
};

export default ROLES;
